### ISSUE TITLE
Inconsistent prefixing

### ISSUE THREAD

**Issue by jamesamcl** [marvinm2/AOPWikiRDF#23]
Sometimes the value of `cheminf:000407` is prefixed, sometimes it isn't. So I think about using `dc:identifier` instead, but then sometimes that is prefixed and sometimes it is _double_ prefixed.

```
chebi:5009      a       cheminf:000407 ;
        cheminf:000407  "5009";
        dc:identifier   "chebi:5009";
        dc:source       "ChEBI".

chebi:CHEBI:5009        a       cheminf:000407 ;
        cheminf:000407  "CHEBI:5009";
        dc:identifier   "chebi:CHEBI:5009";
        dc:source       "ChEBI".
```

**Comment by marvinm2** [comment]
Dear @jamesamcl , thank you for filing this issue! This was indeed caused by the ID mapping tool returning 2 formats of the ChEBI ID (with and without "CHEBI:", so these were parsed double. I corrected the issue and made sure that all "CHEBI" mappings are ignored, leaving the numeric ones which will become "chebi:####" as intended.
